'use client';

import { useState, useEffect, useRef } from 'react';
import { useSession, signIn, signOut } from 'next-auth/react';
import { LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, BarChart, Bar, PieChart, Pie, Cell } from 'recharts';

export default function Home() {
  const { data: session, status } = useSession();
  
  // Chat state
  const [messages, setMessages] = useState<any[]>([]);
  const [newMessage, setNewMessage] = useState('');
  const [isAiTyping, setIsAiTyping] = useState(false);
  const [usageData, setUsageData] = useState<{used: number, limit: number, remaining: number} | null>(null);
  const messagesEndRef = useRef<HTMLDivElement>(null);

  // Auth state
  const [authMode, setAuthMode] = useState<'login' | 'register'>('login');
  const [formData, setFormData] = useState({
    email: '',
    password: '',
    firstName: '',
    lastName: '',
  });
  const [formErrors, setFormErrors] = useState<Record<string, string>>({});
  const [isSubmitting, setIsSubmitting] = useState(false);

  // Dynamic dashboard state - generated by AI responses
  const [dashboardData, setDashboardData] = useState<any>(null);
  const [showDashboard, setShowDashboard] = useState(false);

  // Load chat history on mount
  useEffect(() => {
    if (session && messages.length === 0) {
      loadChatHistory();
    }
  }, [session]);

  // Auto scroll to bottom when new messages arrive
  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages, isAiTyping]);

  const loadChatHistory = async () => {
    try {
      const response = await fetch('/api/chat?limit=50');
      const result = await response.json();
      
      if (result.success && result.data) {
        const formattedMessages = result.data.messages.map((msg: any) => ({
          id: msg.id,
          text: msg.content,
          sender: msg.role.toLowerCase() === 'user' ? 'user' : 'ai',
          timestamp: new Date(msg.timestamp),
        }));
        setMessages(formattedMessages);
        setUsageData(result.data.usage);
      }
    } catch (error) {
      console.error('Error loading chat history:', error);
      initializeChat();
    }
  };

  const initializeChat = () => {
    const welcomeMessage = {
      id: Date.now(),
      text: `¡Hola! 👋 Soy tu asistente financiero personal con IA. Puedo ayudarte a:\n\n💳 Registrar gastos e ingresos\n📊 Crear y revisar presupuestos\n🎯 Establecer y seguir metas financieras\n📈 Analizar tu situación económica\n\n¿En qué puedo ayudarte hoy?`,
      sender: 'ai',
      timestamp: new Date(),
    };
    setMessages([welcomeMessage]);
  };

  const sendMessage = async () => {
    if (!newMessage.trim() || isAiTyping) return;

    const userMessage = {
      id: Date.now(),
      text: newMessage.trim(),
      sender: 'user',
      timestamp: new Date(),
    };

    setMessages(prev => [...prev, userMessage]);
    setNewMessage('');
    setIsAiTyping(true);

    try {
      const response = await fetch('/api/chat', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          message: userMessage.text,
        }),
      });

      const result = await response.json();

      if (result.success && result.data?.message) {
        const aiMessage = {
          id: result.data.messageId || Date.now() + 1,
          text: result.data.message,
          sender: 'ai',
          timestamp: new Date(result.data.timestamp),
          functionCalled: result.data.functionCalled,
        };
        
        setMessages(prev => [...prev, aiMessage]);
        setUsageData(result.data.usage);

        // If a function was called, might want to refresh dashboard
        if (result.data.functionCalled && ['getFinancialSummary', 'getBudgets', 'getGoals', 'getTransactions'].includes(result.data.functionCalled)) {
          setShowDashboard(true);
        }
      } else {
        throw new Error(result.error || 'No response from AI');
      }
    } catch (error) {
      console.error('Error calling AI:', error);
      
      const fallbackMessage = {
        id: Date.now() + 1,
        text: "Disculpa, estoy teniendo problemas técnicos 🤖 ¿Puedes intentar de nuevo?",
        sender: 'ai',
        timestamp: new Date(),
      };
      
      setMessages(prev => [...prev, fallbackMessage]);
    } finally {
      setIsAiTyping(false);
    }
  };

  const handleQuickAction = (action: string) => {
    setNewMessage(action);
  };

  const clearChat = async () => {
    if (confirm('¿Borrar historial de chat? Esta acción no se puede deshacer.')) {
      setMessages([]);
      setShowDashboard(false);
      initializeChat();
    }
  };

  // Auth form handlers
  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setFormData(prev => ({
      ...prev,
      [e.target.name]: e.target.value,
    }));
    if (formErrors[e.target.name]) {
      setFormErrors(prev => ({ ...prev, [e.target.name]: '' }));
    }
  };

  const validateForm = () => {
    const errors: Record<string, string> = {};

    if (!formData.email) {
      errors.email = 'Email es requerido';
    } else if (!/\S+@\S+\.\S+/.test(formData.email)) {
      errors.email = 'Email inválido';
    }

    if (!formData.password) {
      errors.password = 'Contraseña es requerida';
    } else if (formData.password.length < 6) {
      errors.password = 'Contraseña debe tener al menos 6 caracteres';
    }

    if (authMode === 'register') {
      if (!formData.firstName) errors.firstName = 'Nombre es requerido';
      if (!formData.lastName) errors.lastName = 'Apellido es requerido';
    }

    setFormErrors(errors);
    return Object.keys(errors).length === 0;
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!validateForm()) return;

    setIsSubmitting(true);

    try {
      if (authMode === 'login') {
        const result = await signIn('credentials', {
          email: formData.email,
          password: formData.password,
          redirect: false,
        });

        if (result?.error) {
          setFormErrors({ submit: 'Email o contraseña incorrectos' });
          setIsSubmitting(false);
          return;
        }
      } else {
        const response = await fetch('/api/auth/register', {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
          },
          body: JSON.stringify(formData),
        });

        const result = await response.json();

        if (!response.ok) {
          setFormErrors({ submit: result.error || 'Error en el registro' });
          setIsSubmitting(false);
          return;
        }

        const signInResult = await signIn('credentials', {
          email: formData.email,
          password: formData.password,
          redirect: false,
        });

        if (signInResult?.error) {
          setFormErrors({ submit: 'Registro exitoso! Intenta iniciar sesión.' });
          setAuthMode('login');
          setIsSubmitting(false);
          return;
        }
      }
    } catch (error) {
      setFormErrors({ submit: 'Algo salió mal' });
    } finally {
      setIsSubmitting(false);
    }
  };

  const handleLogout = async () => {
    await signOut();
    setMessages([]);
    setDashboardData(null);
    setShowDashboard(false);
    setUsageData(null);
    setFormData({ email: '', password: '', firstName: '', lastName: '' });
  };

  // Loading screen
  if (status === "loading") {
    return (
      <div className="min-h-screen bg-gradient-to-br from-blue-50 via-white to-purple-50 flex items-center justify-center">
        <div className="text-center">
          <div className="w-16 h-16 bg-gradient-to-br from-blue-500 to-purple-600 rounded-full flex items-center justify-center mb-4 mx-auto animate-pulse">
            <span className="text-3xl">💰</span>
          </div>
          <h2 className="text-gray-800 text-xl font-semibold">Cargando MoneyGuyAI...</h2>
          <p className="text-gray-600 mt-2">Tu asistente financiero inteligente</p>
        </div>
      </div>
    );
  }

  // Auth Form
  if (!session) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-blue-50 via-white to-purple-50 flex items-center justify-center p-4">
        <div className="bg-white rounded-2xl shadow-2xl w-full max-w-md p-8 border border-gray-100">
          <div className="text-center mb-6">
            <div className="w-16 h-16 mx-auto mb-4 bg-gradient-to-br from-blue-500 to-purple-600 rounded-full flex items-center justify-center">
              <span className="text-3xl">💰</span>
            </div>
            <h1 className="text-2xl font-bold text-gray-900">
              {authMode === 'login' ? 'Bienvenido de Nuevo' : 'Únete a MoneyGuyAI'}
            </h1>
            <p className="text-gray-600 mt-2">
              {authMode === 'login' 
                ? 'Inicia sesión en tu cuenta' 
                : 'Crea tu cuenta para empezar'
              }
            </p>
          </div>

          <form onSubmit={handleSubmit} className="space-y-4">
            {authMode === 'register' && (
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">Nombre</label>
                  <input
                    name="firstName"
                    value={formData.firstName}
                    onChange={handleInputChange}
                    className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent transition-colors"
                    placeholder="Juan"
                  />
                  {formErrors.firstName && <p className="text-sm text-red-600 mt-1">{formErrors.firstName}</p>}
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">Apellido</label>
                  <input
                    name="lastName"
                    value={formData.lastName}
                    onChange={handleInputChange}
                    className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent transition-colors"
                    placeholder="Pérez"
                  />
                  {formErrors.lastName && <p className="text-sm text-red-600 mt-1">{formErrors.lastName}</p>}
                </div>
              </div>
            )}

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">Email</label>
              <input
                name="email"
                type="email"
                value={formData.email}
                onChange={handleInputChange}
                className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent transition-colors"
                placeholder="tu@ejemplo.com"
              />
              {formErrors.email && <p className="text-sm text-red-600 mt-1">{formErrors.email}</p>}
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">Contraseña</label>
              <input
                name="password"
                type="password"
                value={formData.password}
                onChange={handleInputChange}
                className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent transition-colors"
                placeholder="Ingresa tu contraseña"
              />
              {formErrors.password && <p className="text-sm text-red-600 mt-1">{formErrors.password}</p>}
            </div>

            {formErrors.submit && (
              <div className="text-sm text-red-600 text-center">{formErrors.submit}</div>
            )}

            <button 
              type="submit" 
              className="w-full py-3 px-4 bg-gradient-to-r from-blue-500 to-purple-600 text-white font-semibold rounded-lg hover:from-blue-600 hover:to-purple-700 focus:ring-4 focus:ring-blue-200 transition-all duration-200 disabled:opacity-50" 
              disabled={isSubmitting}
            >
              {isSubmitting 
                ? (authMode === 'login' ? 'Iniciando sesión...' : 'Creando cuenta...') 
                : (authMode === 'login' ? 'Iniciar Sesión' : 'Crear Cuenta')
              }
            </button>
          </form>

          <div className="text-center mt-6">
            <p className="text-sm text-gray-600">
              {authMode === 'login' ? "¿No tienes cuenta? " : "¿Ya tienes cuenta? "}
              <button
                onClick={() => setAuthMode(authMode === 'login' ? 'register' : 'login')}
                className="text-blue-600 hover:text-blue-700 font-medium transition-colors"
              >
                {authMode === 'login' ? 'Regístrate' : 'Inicia sesión'}
              </button>
            </p>
          </div>
        </div>
      </div>
    );
  }

  // Quick actions for better UX
  const quickActions = [
    "Registra un gasto de 25€ en comida",
    "¿Cómo van mis presupuestos?",
    "Muéstrame mi resumen financiero",
    "Crear meta de ahorro para vacaciones",
    "Ver mis últimas transacciones"
  ];

  // Main Chat Interface
  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 via-white to-purple-50">
      {/* Header */}
      <header className="bg-white/80 backdrop-blur-md border-b border-gray-200 sticky top-0 z-10">
        <div className="max-w-4xl mx-auto px-4 py-4 flex items-center justify-between">
          <div className="flex items-center space-x-3">
            <div className="w-10 h-10 bg-gradient-to-br from-blue-500 to-purple-600 rounded-full flex items-center justify-center">
              <span className="text-xl">💰</span>
            </div>
            <div>
              <h1 className="text-xl font-bold text-gray-900">MoneyGuyAI</h1>
              <p className="text-sm text-gray-600">Tu asistente financiero inteligente</p>
            </div>
          </div>
          
          <div className="flex items-center space-x-4">
            {usageData && (
              <div className="text-sm text-gray-600">
                {usageData.remaining}/{usageData.limit} mensajes
              </div>
            )}
            <button
              onClick={clearChat}
              className="text-gray-500 hover:text-red-600 transition-colors"
              title="Limpiar chat"
            >
              🗑️
            </button>
            <button
              onClick={handleLogout}
              className="text-gray-500 hover:text-gray-700 transition-colors"
              title="Cerrar sesión"
            >
              🚪
            </button>
          </div>
        </div>
      </header>

      {/* Main Content */}
      <main className="max-w-4xl mx-auto px-4 py-6">
        <div className="grid gap-6 lg:grid-cols-3">
          {/* Chat Interface - Takes up 2/3 on large screens */}
          <div className="lg:col-span-2">
            <div className="bg-white rounded-2xl shadow-lg border border-gray-200 h-[calc(100vh-200px)] flex flex-col">
              {/* Chat Header */}
              <div className="p-4 border-b border-gray-200">
                <h2 className="font-semibold text-gray-900">Chat con IA</h2>
                <p className="text-sm text-gray-600">Pregúntame sobre tus finanzas</p>
              </div>

              {/* Messages Area */}
              <div className="flex-1 overflow-y-auto p-4 space-y-4">
                {messages.map((message) => (
                  <div
                    key={message.id}
                    className={`flex ${message.sender === 'user' ? 'justify-end' : 'justify-start'}`}
                  >
                    <div className={`max-w-[80%] rounded-xl p-3 ${
                      message.sender === 'user'
                        ? 'bg-gradient-to-r from-blue-500 to-purple-600 text-white'
                        : 'bg-gray-100 text-gray-900'
                    }`}>
                      <p className="text-sm leading-relaxed whitespace-pre-wrap">{message.text}</p>
                      <div className="flex justify-between items-center mt-2">
                        <p className={`text-xs ${
                          message.sender === 'user' ? 'text-blue-100' : 'text-gray-500'
                        }`}>
                          {message.timestamp.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
                        </p>
                        {message.functionCalled && (
                          <span className="text-xs bg-black/10 px-2 py-1 rounded">
                            {message.functionCalled}
                          </span>
                        )}
                      </div>
                    </div>
                  </div>
                ))}

                {/* AI Typing Indicator */}
                {isAiTyping && (
                  <div className="flex justify-start">
                    <div className="bg-gray-100 rounded-xl p-3 max-w-[80%]">
                      <div className="flex space-x-1">
                        <div className="w-2 h-2 bg-gray-400 rounded-full animate-bounce"></div>
                        <div className="w-2 h-2 bg-gray-400 rounded-full animate-bounce" style={{ animationDelay: '0.1s' }}></div>
                        <div className="w-2 h-2 bg-gray-400 rounded-full animate-bounce" style={{ animationDelay: '0.2s' }}></div>
                      </div>
                    </div>
                  </div>
                )}
                
                <div ref={messagesEndRef} />
              </div>

              {/* Message Input */}
              <div className="p-4 border-t border-gray-200">
                <div className="flex space-x-2">
                  <input
                    type="text"
                    value={newMessage}
                    onChange={(e) => setNewMessage(e.target.value)}
                    onKeyPress={(e) => e.key === 'Enter' && sendMessage()}
                    placeholder="Escribe tu pregunta o solicitud..."
                    className="flex-1 px-4 py-2 border border-gray-300 rounded-xl focus:ring-2 focus:ring-blue-500 focus:border-transparent transition-colors"
                    disabled={isAiTyping}
                  />
                  <button
                    onClick={sendMessage}
                    disabled={!newMessage.trim() || isAiTyping}
                    className={`px-4 py-2 rounded-xl font-medium transition-all ${
                      newMessage.trim() && !isAiTyping
                        ? 'bg-gradient-to-r from-blue-500 to-purple-600 text-white hover:from-blue-600 hover:to-purple-700'
                        : 'bg-gray-300 text-gray-500 cursor-not-allowed'
                    }`}
                  >
                    {isAiTyping ? '⏳' : '📤'}
                  </button>
                </div>
              </div>
            </div>
          </div>

          {/* Sidebar - Quick actions and status */}
          <div className="space-y-6">
            {/* Quick Actions */}
            <div className="bg-white rounded-2xl shadow-lg border border-gray-200 p-4">
              <h3 className="font-semibold text-gray-900 mb-3">Acciones Rápidas</h3>
              <div className="space-y-2">
                {quickActions.map((action, index) => (
                  <button
                    key={index}
                    onClick={() => handleQuickAction(action)}
                    className="w-full text-left p-3 bg-gray-50 hover:bg-blue-50 rounded-xl transition-colors text-sm"
                  >
                    💡 {action}
                  </button>
                ))}
              </div>
            </div>

            {/* Usage Stats */}
            {usageData && (
              <div className="bg-white rounded-2xl shadow-lg border border-gray-200 p-4">
                <h3 className="font-semibold text-gray-900 mb-3">Uso Diario</h3>
                <div className="space-y-2">
                  <div className="flex justify-between text-sm">
                    <span>Mensajes enviados:</span>
                    <span className="font-medium">{usageData.used}</span>
                  </div>
                  <div className="flex justify-between text-sm">
                    <span>Mensajes restantes:</span>
                    <span className="font-medium text-blue-600">{usageData.remaining}</span>
                  </div>
                  <div className="w-full bg-gray-200 rounded-full h-2 mt-2">
                    <div 
                      className="bg-gradient-to-r from-blue-500 to-purple-600 h-2 rounded-full transition-all duration-300"
                      style={{ width: `${(usageData.used / usageData.limit) * 100}%` }}
                    />
                  </div>
                </div>
              </div>
            )}

            {/* Dynamic Dashboard Preview */}
            {showDashboard && (
              <div className="bg-white rounded-2xl shadow-lg border border-gray-200 p-4">
                <h3 className="font-semibold text-gray-900 mb-3">Vista Rápida</h3>
                <p className="text-sm text-gray-600">
                  Dashboard actualizado después de la última consulta
                </p>
                <button
                  onClick={() => handleQuickAction("Muéstrame mi resumen financiero completo")}
                  className="w-full mt-3 py-2 bg-gradient-to-r from-blue-500 to-purple-600 text-white rounded-lg hover:from-blue-600 hover:to-purple-700 transition-all text-sm font-medium"
                >
                  Ver Resumen Completo
                </button>
              </div>
            )}
          </div>
        </div>
      </main>
    </div>
  );
}